import './globals.css'
import type { Metadata } from 'next'
import localFont from 'next/font/local'
import { Navbar } from './_components/navbar/navbar'
import { Toaster } from 'sonner'
import { ThemeProvider } from '@/components/theme-provider'

const Onest = localFont({
	src: '../public/Onest-vfw.ttf',
	display: 'auto',
})

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

export default function RootLayout({
	children,
}: {
	children: React.ReactNode
}) {
	return (
		<html lang='en'>
			<body className={Onest.className}>
				<ThemeProvider
					attribute='class'
					defaultTheme='system'
					enableSystem>
					<Navbar />
					{children}
					<Toaster />
				</ThemeProvider>
			</body>
		</html>
	)
}
